# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYLpj8jwLJR17fcte2rfbb3u6vyoUpi7
"""

q = input().split()
w = input().split()
x1, y1 = int(q[0]), int(q[1])
x2, y2 = int(w[0]), int(w[1])
if x1 == x2 and y1 == y2:
  print('No')
elif checkerboard[x2][y2] == 1:
  print('No')
else:
  if abs(x1-x2)<=1 and abs(y1-y2)<=1:
    print('Yes')
  else:
    print('No')